<?php

return [
    [
        "title"            => "Spotify Web",
        "author"           => "Davide Farci",
        "creation_date"    => "2023-03-22",
        "last_update"      => "2023-03-27",
        "collaborators"    => "",
        "description"      => "A clone of Spotify Web",
        "languages"        => "HTML, CSS",
        "link_github"      => "https://github.com/DavideFarci/html-css-spotifyweb.git",
        "type_id"             => "1",
    ],
    [
        "title"            => "Campominato",
        "author"           => "Davide Farci",
        "creation_date"    => "2023-04-06",
        "last_update"      => "2023-05-01",
        "collaborators"    => "",
        "description"      => "A clone of Minefield",
        "languages"        => "HTML, CSS, JS ",
        "link_github"      => "https://github.com/DavideFarci/js-campominato-dom.git",
        "type_id"             => "1",
    ],
    [
        "title"            => "Social Post",
        "author"           => "Davide Farci",
        "creation_date"    => "2023-05-03",
        "last_update"      => "2023-05-03",
        "collaborators"    => "",
        "description"      => "A clone of Facebook",
        "languages"        => "HTML, CSS, JS",
        "link_github"      => "https://github.com/DavideFarci/js-social-posts.git",
        "type_id"          => "1",
    ],
    [
        "title"            => "BoolzApp",
        "author"           => "Davide Farci",
        "creation_date"    => "2023-05-10",
        "last_update"      => "2023-06-06",
        "collaborators"    => "",
        "description"      => "A clone of WhatsApp",
        "languages"        => "HTML, CSS, JS",
        "link_github"      => "https://github.com/DavideFarci/vue-boolzapp.git",
        "type_id"          => "1",
    ],
    [
        "title"            => "BoolFlix",
        "author"           => "Davide Farci",
        "creation_date"    => "2023-05-24",
        "last_update"      => "2023-06-26",
        "collaborators"    => "",
        "description"      => "A clone of Nelflix",
        "languages"        => "HTML, JS, VUE",
        "link_github"      => "https://github.com/DavideFarci/vite-boolflix.git",
        "type_id"          => "1",
    ],
    [
        "title"            => "Project Html-VueJs",
        "author"           => "Davide Farci",
        "creation_date"    => "2023-05-29",
        "last_update"      => "2023-06-05",
        "collaborators"    => "",
        "description"      => "A clone of a Website",
        "languages"        => "HTML, VUE",
        "link_github"      => "https://github.com/DavideFarci/proj-html-vuejs.git",
        "type_id"          => "1",
    ],
    [
        "title"            => "DC Comics",
        "author"           => "Davide Farci",
        "creation_date"    => "2023-06-29",
        "last_update"      => "2023-07-03",
        "collaborators"    => "",
        "description"      => "A clone of a Website of DC Comics",
        "languages"        => "PHP, BLADE",
        "link_github"      => "https://github.com/DavideFarci/laravel-dc-comics.git",
        "type_id"          => "2",
    ],
    [
        "title"            => "Laravel Boolean",
        "author"           => "Simone Ricco",
        "creation_date"    => "2023-07-04",
        "last_update"      => "2023-07-004",
        "collaborators"    => "Antonio D'Angelo, Luca Casamassima, Davide Farci, Loris Marzocchi",
        "description"      => "A invoices organizer",
        "languages"        => "PHP, BLADE, JS",
        "link_github"      => "https://github.com/SimoneRicco/laravel-boolean.git",
        "type_id"          => "3",
    ],
];
